### ISSUE TITLE
Sintesis_Gestion_de_proyectos_de_Software

### ISSUE THREAD

**Issue by Nelsy21** [SistemasTecTlaxiaco/actividad-3-sintesis-Nelsy21#1]
[Sintesis_Unidad1_Gestion_de_Proyectos_de_Sftware.pdf](https://github.com/user-attachments/files/16821573/Sintesis_Unidad1_Gestion_de_Proyectos_de_Sftware.pdf)

**Comment by isairey** [comment]
Preparación  e identificación: Falto Bibliografía 18
Estructura: 60
Presentación: 10
Calificación: 88

**Comment by josealfredo79** [comment]
Revisado..
